### ISSUE TITLE
Dialog not being reset when searching openings by name

### ISSUE THREAD

**Issue by programarivm** [chesslablab/redux-chess#259]
Steps to reproduce:

1. Click on **Opening Search** > **Name**
2. Type **Sicilian** in the Name field and then click on **Search**
3. Load **A00, Hungarian Opening: Sicilian Invitation**

Then repeat:

4. Click on **Opening Search** > **Name**

At this point, the dialog will display the results of the previous search, however, no search results should be displayed when opening a search dialog. The buggy behavior is described in the GIF below.

![output](https://user-images.githubusercontent.com/4062000/151412383-82adf4c3-5626-4d0d-b625-daadb30ba768.gif)
**Figure 1**. No results should be displayed when opening the **Opening Search** dialog to search by name.

Happy coding and learning, and keep it up.

**Comment by RebeccaTurk** [comment]
Hi @programarivm. I'm interested in picking this up. Could you please assign to me?

**Comment by programarivm** [comment]
@RebeccaTurk welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/redux-chess/blob/master/CONTRIBUTING.md).

Keep it up, and happy learning and coding!

**Comment by RebeccaTurk** [comment]
Hi @programarivm , it looks like this is resolved, please let me know if otherwise. How can I keep myself posted on future issues in this project? It was taking me some time to set up the env, but now that I've invested that, I would like to keep my eyes open for future contribution opps. Please let me know--thanks!

**Comment by programarivm** [comment]
Thank you, any feedback on setting up the [`testing-redux-chess`](https://github.com/chesslablab/testing-redux-chess) app is very much appreciated.

These are some good first issues still to be solved: 

- https://github.com/chesslablab/redux-chess/issues/240
- https://github.com/chesslablab/redux-chess/issues/248
- https://github.com/chesslablab/redux-chess/issues/239

Just comment on the issue you'd want to be assigned to: 

> Happy learning and coding!
